name: Publicador Automatico Ingles para Ti

on:
  schedule:
    # 7:30 AM Sonora (14:30 UTC)
    - cron: '30 14 * * *'
    # 1:30 PM Sonora (20:30 UTC)
    - cron: '30 20 * * *'
    # 6:30 PM Sonora (01:30 UTC del día siguiente)
    - cron: '30 1 * * *'
    # 9:30 PM Sonora (04:30 UTC del día siguiente)
    - cron: '30 4 * * *'
  
  # Mantiene la opción de ejecutarlo manualmente si lo necesitas
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script de publicación
        env:
          PAGE_ID_3: ${{ secrets.PAGE_ID_3 }}
          ACCESS_TOKEN_7: ${{ secrets.ACCESS_TOKEN_7 }}
        run: python publicar.py

      - name: Guardar cambios en el JSON
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add publicaciones.json
          git commit -m "Auto-update: post eliminado de la cola" || exit 0
          git push